# Generated by Django 5.1.2 on 2024-10-30 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('isbn', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=20)),
                ('nome_autor', models.CharField(max_length=40)),
                ('data_lancamento', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'livros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PedidoLivro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.livros')),
            ],
            options={
                'db_table': 'pedido_livro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('livros', models.ManyToManyField(through='playground.PedidoLivro', to='playground.livros')),
            ],
            options={
                'db_table': 'pedidos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pedidolivro',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.pedidos'),
        ),
    ]
