# Generated by Django 5.1.2 on 2024-10-30 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Livro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(choices=[('FICCAO_CIENTIFICA', 'Ficção Científica'), ('ROMANCE', 'Romance'), ('FANTASIA', 'Fantasia'), ('BIOGRAFIA', 'Biografia'), ('AVENTURA', 'Aventura'), ('HISTORIA', 'História'), ('MISTERIO', 'Mistério'), ('TERROR', 'Terror'), ('AUTOAJUDA', 'Autoajuda'), ('EDUCACIONAL', 'Educacional')], max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categoria_livro',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='playground.categoria_livro'),
        ),
    ]
