# Generated by Django 5.1.2 on 2024-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_pedido_options_alter_produto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(related_name='pedidos', to='playground.produto'),
        ),
    ]
