# Generated by Django 5.1.2 on 2024-10-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_categoria_livro_alter_livros_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.CharField(choices=[('FICCAO_CIENTIFICA', 'Ficção Científica'), ('ROMANCE', 'Romance'), ('FANTASIA', 'Fantasia'), ('BIOGRAFIA', 'Biografia'), ('AVENTURA', 'Aventura'), ('HISTORIA', 'História'), ('MISTERIO', 'Mistério'), ('TERROR', 'Terror'), ('AUTOAJUDA', 'Autoajuda'), ('EDUCACIONAL', 'Educacional')], max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Categoria_Livro',
        ),
    ]
