# Generated by Django 5.1.2 on 2024-10-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_pedido_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.produto')),
            ],
            options={
                'db_table': 'pedido_produto',
                'managed': True,
            },
        ),
    ]
