# Generated by Django 5.1.2 on 2024-11-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_pedidos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='data_pedido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='hora_pedido',
            field=models.CharField(default='', max_length=100),
        ),
    ]
