# Generated by Django 5.1.2 on 2024-11-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_alter_livros_foto_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='data_pedido_entregue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='status_pedido',
            field=models.BooleanField(default=False),
        ),
    ]
