# Generated by Django 5.1.2 on 2024-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_pedidos_data_pedido_entregue_pedidos_status_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='endereco_entrega',
            field=models.CharField(default='Roma, Italy', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='endereco_saida',
            field=models.CharField(default='Brasilia, Brasil', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido_entregue',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='hora_pedido',
            field=models.CharField(max_length=100),
        ),
    ]
